version: '3.8'

services:
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    container_name: note-board-frontend
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://backend:3000/api
    depends_on:
      - backend
    networks:
      - note-board-network

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: note-board-backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=mysql://root:password@mysql:3306/note_board
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - mysql
    networks:
      - note-board-network

  mysql:
    image: mysql:8.0
    container_name: note-board-mysql
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=note_board
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - note-board-network

networks:
  note-board-network:
    driver: bridge

volumes:
  mysql_data: 