version: '3.8'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: note-board-backend-dev
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=mysql://root:password@mysql:3306/note_board
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - note-board-network

  prisma-studio:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: note-board-prisma-studio
    restart: unless-stopped
    ports:
      - "5555:5555"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=mysql://root:password@mysql:3306/note_board
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      mysql:
        condition: service_healthy
      backend:
        condition: service_started
    networks:
      - note-board-network
    command: npx prisma studio --hostname 0.0.0.0 --port 5555 --browser none

  mysql:
    image: mysql:8.0
    container_name: note-board-mysql-dev
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=note_board
    ports:
      - "3307:3306"
    volumes:
      - mysql_data_dev:/var/lib/mysql
    networks:
      - note-board-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-ppassword"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 5s

networks:
  note-board-network:
    driver: bridge

volumes:
  mysql_data_dev: 