FROM node:18

WORKDIR /app

COPY package*.json ./

# Install dependencies with specific handling for bcrypt
RUN npm install --no-optional

# Install dos2unix for fixing line endings
RUN apt-get update && apt-get install -y dos2unix

# Copy scripts first and make them executable
COPY ./scripts ./scripts/
RUN chmod +x ./scripts/*.sh
RUN find /app/scripts -type f -name "*.sh" -exec dos2unix {} \;

# Copy rest of the application
COPY . .

# Generate Prisma client
RUN npx prisma generate

EXPOSE 3000

CMD ["bash", "./scripts/docker-entrypoint.sh"]