FROM node:18

WORKDIR /app

COPY package*.json ./

RUN npm install

# Rebuild bcrypt for the container architecture
RUN npm rebuild bcrypt --build-from-source

# Copy scripts first and make them executable
COPY ./scripts ./scripts/
RUN chmod +x ./scripts/start-dev.sh

# Copy rest of the application
COPY . .

# Sinh client Prisma
RUN npx prisma generate

EXPOSE 3000

CMD ["sh", "./scripts/start-dev.sh"]